<?php

include_once 'database.php';

if (isset($_POST['func'])) {
	
	if ("fireExComp" == $_POST['func']) {
		fireExchangeComplaint();
	}
	else if ("cancelTrade" == $_POST['func']) {
		// cancelTradeOrder();
	}
	else if ("startTrade" == $_POST['func']) {
		// startTradeOrder();
	}
	else if ("saveCredit" == $_POST['func']) {
		// saveCredit();
	}
	else if ("confirmPayment" == $_POST['func']) {
		// confirmTradeOrderPay();
	}
	else if ("abandonPayment" == $_POST['func']) {
		// abandonTradeOrderPay();
	}
	else if ("confirmReceive" == $_POST['func']) {
		// confirmReceiveMoney();
	}
}

/*
 * 发起交易投诉，主要应对对方没打款或少打款的情况。
 */
function fireExchangeComplaint()
{	
	include 'regtest.php';
	include 'constant.php';
	
	session_start();
	if (!$_SESSION["isLogin"]) {
		echo json_encode(array('error'=>'true','error_code'=>'20','error_msg'=>'请先登录！'));
		return;
	}
	
	$type = trim(htmlspecialchars($_POST["t"]));
	$issueId = trim(htmlspecialchars($_POST['idx']));	// 交易订单的index
	$desc = trim(htmlspecialchars($_POST['desc']));
	
	if ($complainTCreditTrade != $type) {
		echo json_encode(array('error'=>'true','error_code'=>'1','error_msg'=>'类型出错，请稍后重试！'));
		return;		
	}
	
	if (strlen($desc) <= 0) {
		echo json_encode(array('error'=>'true','error_code'=>'2','error_msg'=>'无效的问题描述，请稍后重试！'));
		return;		
	}
	
	$con = connectToDB();
	if (!$con)
	{
		echo json_encode(array('error'=>'true','error_code'=>'30','error_msg'=>'设置失败，请稍后重试！'));
		return;
	}
	else 
	{
		$userid = $_SESSION['userId'];
		$nickname = $_SESSION['nickname'];
		$phone = $_SESSION['phonenum'];
		
		$res = mysqli_query($con, "select * from CreditTrade where IdxId='$issueId'");
		if (!$res || mysqli_num_rows($res) <= 0) {
			echo json_encode(array('error'=>'true','error_code'=>'31','error_msg'=>'查找不到投诉的交易订单，请稍后重试！'));	
			return;
		}
		$row = mysqli_fetch_assoc($res);
		$tradeId = $row["TradeId"];

		if ($userid != $row["SellerId"]) {
			echo json_encode(array('error'=>'true','error_code'=>'3','error_msg'=>'交易信息有误，请稍后重试！' . $row["SellerId"] . '_' . $userid));
			return;
		}
		
		$respondentId = $row["BuyerId"];
		$res1 = mysqli_query($con, "select * from ClientTable where UserId='$respondentId'");
		if (!$res1 || mysqli_num_rows($res1) <= 0) {
			echo json_encode(array('error'=>'true','error_code'=>'4','error_msg'=>'查找被投诉人信息出错，请稍后重试！' . $row["SellerId"] . '_' . $userid));
			return;
		}
		$row1 = mysqli_fetch_assoc($res1);
		$respondNName = $row1["NickName"];
		$respondPhone = $row1["PhoneNum"];
		
		$result = createComplaintTable($con);
		if (!$result) {
			echo json_encode(array('error'=>'true','error_code'=>'32','error_msg'=>'库操作失败，请稍后重试！'));
			return;
		}
		
		$now = time();
		
		// generate trade id
		date_default_timezone_set('PRC');
		$timeStr = date("YmdHis", $now);
		$compId = '';
		$isCompIdSet = false;
		$i = 0;
		// check if compId generated by rand is used, only try 10 times to avoid occoping computing resources
		while ($i < 10) {
			
			$num = rand(1, 99);
			if ($num < 10) {
				$compId = $timeStr . '0' . $num;
			}
			else {
				$compId = $timeStr . $num;
			}
			
			$res1 = mysqli_query($con, "select * from Complaint where CompId='$compId'");
			if ($res1) {
				if (mysqli_num_rows($res1) > 0) {
					
					// $compId used, choose a new one
				}
				else {
					// $tradeId not used, break
					$isCompIdSet = true;
					break;
				}
			}
			
			$i = $i + 1;
		}
		
		if (!$isCompIdSet) {
			echo json_encode(array('error'=>'true','error_code'=>'5','error_msg'=>'生成投诉号出错，请稍后重试！'));
			return;
		}

		$res2 = mysqli_query($con, "insert into Complaint (CompId, Type, RelatedIdx, RelatedIssueId, ComplainantId, CompNickname, CompPhoneNum, RespondentId, RespNickname, RespPhoneNum, IssueDesc, IssueTime, Status)
								values($compId, $complainTCreditTrade, $issueId, $tradeId, $userid, '$nickname', $phone, $respondentId, '$respondNName', $respondPhone, '$desc', $now, $complainSOPen)");
								
		if (!$res2) {
			echo json_encode(array('error'=>'true','error_code'=>'6','error_msg'=>'发起投诉失败，请稍后重试！','sql_error'=>mysqli_error($con)));
			return;
		}
	}
	
	echo json_encode(array('error'=>'false'));
}
	
?>